import { Property } from '../types';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Luxury Villa with Pool',
    description: 'A beautiful luxury villa located in the heart of the city.',
    price: 1250000,
    currency: 'USD',
    address: '123 Luxury Lane',
    city: 'Beverly Hills',
    state: 'CA',
    zipCode: '90210',
    country: 'USA',
    type: 'house',
    status: 'available',
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 4500,
    yearBuilt: 2018,
    images: ['/images/property-1.jpg'],
    features: ['Pool', 'Garage', 'Garden', 'Smart Home'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Modern Downtown Apartment',
    description: 'A sleek apartment with stunning city views.',
    price: 450000,
    currency: 'USD',
    address: '456 Main St, Apt 12B',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    type: 'apartment',
    status: 'pending',
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    yearBuilt: 2020,
    images: ['/images/property-2.jpg'],
    features: ['Gym', 'Doorman', 'Rooftop Deck'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Cozy Suburban House',
    description: 'Perfect family home with a large backyard.',
    price: 650000,
    currency: 'USD',
    address: '789 Oak Ave',
    city: 'Austin',
    state: 'TX',
    zipCode: '73301',
    country: 'USA',
    type: 'house',
    status: 'sold',
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2800,
    yearBuilt: 2010,
    images: ['/images/property-3.jpg'],
    features: ['Fireplace', 'Large Yard', 'Remodeled Kitchen'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
